chore: update the js v5 page
zksync-sdk/sdk-docs pull request #55
Opened 2024-06-25 13:29 UTC by Ngozi-Txfusion

### What

- **Updated the JS v5 Page:**
  - Revised the content and structure of the JavaScript v5 page to reflect the latest changes and improvements in the SDK, ensuring it provides accurate and up-to-date information for developers.

- **Changed the Feel and Appearance:**
  - Modified the design and layout of the documentation to enhance user experience, making it more visually appealing and easier to navigate.

### Why

- **JS v5 Page Updates:**
  - To provide developers with the most current information and guidance on using JavaScript v5, ensuring that the documentation aligns with the latest SDK version.

- **Feel and Appearance Changes:**
  - To improve the overall user experience by making the documentation more attractive and user-friendly, which helps developers find the information they need more efficiently and enjoyably.

2024-06-25 15:22 UTC, itsacoyote requested changes

2024-06-25 15:22 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/07.utils.md
> +and [`isTypedDataSignatureCorrect`](/sdk/js/ethers/v5/utils#istypeddatasignaturecorrect). Returns true if
```suggestion
and [`isTypedDataSignatureCorrect`](#istypeddatasignaturecorrect). Returns true if
```

2024-06-25 15:22 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/07.utils.md
> +See also [`applyl1tol2alias`](/sdk/js/ethers/v5/utils#applyl1tol2alias).
```suggestion
See also [`applyl1tol2alias`](#applyl1tol2alias).
```

2024-06-25 16:08 UTC, itsacoyote requested changes
You may need to check through the URLs to make sure they're not broken. We also made some changes to URLs for docs.zksync.io. They should redirect to a page, but they might not be the correct up to date page.

2024-06-25 16:08 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/01.features.md
> +team endorses certain types of [paymaster flows](https://docs.zksync.io/build/developer-reference/account-abstraction.html#built-in-paymaster-flows)
```suggestion
team endorses certain types of [paymaster flows](https://docs.zksync.io/build/developer-reference/account-abstraction/paymasters#built-in-paymaster-flows)
```

2024-06-25 16:08 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/01.features.md
> +following way, while paying fees with the [testnet paymaster](https://docs.zksync.io/build/developer-reference/account-abstraction.html#testnet-paymaster):
```suggestion
following way, while paying fees with the [testnet paymaster](https://docs.zksync.io/build/developer-reference/account-abstraction/paymasters#testnet-paymaster):
```

2024-06-25 16:08 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/03.providers.md
> +- **Provider**: Extends [`ethers.JsonRpcProvider`](https://docs.ethers.org/v5/api/providers/jsonrpc/#about-jsonrpcProvider)
It looks like a variety of Ethers docs links are broken, please go through and check that they're up to date.

```suggestion
- **Provider**: Extends [`ethers.JsonRpcProvider`](https://docs.ethers.org/v5/api/providers/jsonrpc-provider/)
```

2024-06-25 16:08 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/05.accounts-l1-l2.md
> +If you need background information on how L1<->L2 interactions work on ZKsync, check out the [Developer Reference](https://docs.zksync.io/build/developer-reference/l1-l2-interop.html).
```suggestion
If you need background information on how L1<->L2 interactions work on ZKsync, check out the [Developer Reference](https://docs.zksync.io/build/developer-reference/l1-l2-interoperability).
```

2024-06-25 16:25 UTC, petarTxFusion submitted a review, later dismissed

2024-06-26 19:19 UTC, itsacoyote requested changes

2024-06-26 19:19 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/02.front-end.md
> +library. Learn the basics of `zksync-ethers` in the [ZKsync Era Features](/sdk/js/ethers/v6/features).
```suggestion
library. Learn the basics of `zksync-ethers` in the [ZKsync Era Features](/sdk/js/ethers/v5/features).
```

2024-06-26 19:19 UTC, itsacoyote commented on content/sdk/10.js/00.ethers/10.v5/03.providers.md
> +Helper function: [toJSON](/sdk/js/ethers/v5/providers#tojson).
```suggestion
Helper function: [toJSON](#tojson).
```

2024-06-27 10:25 UTC, danijelTxFusion approved these changes

2024-06-28 14:50 UTC, itsacoyote approved these changes

2024-06-28 14:50 UTC, merged