fix: update the overview page
zksync-sdk/sdk-docs pull request #92
Opened 2024-08-29 08:38 UTC by Ngozi-Txfusion

## What

- Update the overview page for web3js
- Structure the pages to follow the contribution guideline

## Why

2024-08-29 10:15 UTC, petarTxFusion approved these changes, later dismissed

2024-08-30 09:02 UTC, petarTxFusion submitted a review, later dismissed

2024-09-02 08:47 UTC, danijelTxFusion submitted a review, later dismissed

2024-09-03 19:40 UTC, itsacoyote requested changes

2024-09-03 19:40 UTC, itsacoyote commented on content/10.js/01.web3js/00.index.md
> +## Web3.js plugin for ZKsync
Let's remove this header.

2024-09-03 19:40 UTC, itsacoyote commented on content/10.js/01.web3js/00.index.md
> +Below, you’ll find sections that offer explanations for using the plugin:
Remove this header and line as well.

2024-09-03 19:40 UTC, itsacoyote commented on content/10.js/01.web3js/00.index.md
> +Information on constants, types, and utility functions provided by the plugin.e.
```suggestion
Information on constants, types, and utility functions provided by the plugin.
```

2024-09-04 08:47 UTC, petarTxFusion approved these changes

2024-09-04 13:41 UTC, itsacoyote approved these changes
Thank you and great catch on the headers capitalizations 👍🏻

2024-09-04 13:41 UTC, merged